expo/examples

with-react-native-calendars/README.md, with-react-native-calendars/app.json, with-react-native-calendars/package-lock.json, with-react-native-calendars/package.json
Simple upgrade, everything seems to work fine without any big changes. Also added a direct snack link if that's ok 😄
=> Upgrade `with-react-native-calendars` to Expo SDK 32

with-redux/.babelrc, with-redux/README.md, with-redux/app.json, with-redux/babel.config.js, with-redux/package-lock.json, with-redux/package.json
Me again, with another upgrade to SDK 32 😄
=> Upgrade `with-redux` to Expo SDK 32

with-webbrowser-redirect/README.md, with-webbrowser-redirect/app/.babelrc, with-webbrowser-redirect/app/app.json, with-webbrowser-redirect/app/babel.config.js, with-webbrowser-redirect/app/package-lock.json, with-webbrowser-redirect/app/package.json
=> Upgrade `with-webbrowser-redirect` to Expo SDK 32

with-redux/yarn.lock
=> Redux Example- Update yarn.lock

with-electron/App.tsx, with-electron/app.json, with-electron/package.json, with-electron/yarn.lock
Electron: Update to sdk 36 + some packages + bonus: change gradient colors to expo's white / blue (call me a detail-oriented if you want 😝)
=> Electron: update expo sdk@36 + packages + apply corporate colors to gradient

with-gatsby/src/components/Header.tsx, with-gatsby/src/components/Layout.tsx, with-gatsby/src/components/SEO.tsx
Not sure why propTypes was being used in a typescript project.. I removed them and added interfaces instead. I left the propTypes package as thats need for something i think..?
=> @molebox/add-interfaces: removed propTypes and added interfaces

with-video-background/App.js, with-video-background/README.md, with-video-background/app.json, with-video-background/babel.config.js, with-video-background/package.json
=> Created with-video-background

with-google-vision/App.js, with-google-vision/README.md, with-google-vision/app.json, with-google-vision/babel.config.js, with-google-vision/package.json
=> Created google vision example

with-icons/App.js, with-icons/README.md, with-icons/app.json, with-icons/babel.config.js, with-icons/package.json
=> Created icons example

with-firebase-storage-upload/App.js, with-firebase-storage-upload/README.md, with-firebase-storage-upload/app.json, with-firebase-storage-upload/babel.config.js, with-firebase-storage-upload/package.json
Fixes #83 
Unfortunately, this wasn't working for web. It triggers some issues with the `blob` response. Have to dig deeper what's causing it, maybe using another node fetch library does the trick.
=> feat: add firebase storage upload example

with-victory-native/app.json, with-victory-native/package.json, with-victory-native/yarn.lock
upgrade with-victory-native example to expo 36
=> [with-victory-native] upgrade to expo 36

with-styled-components/App.js, with-styled-components/README.md, with-styled-components/package.json
=> Created styled-components example

blank/App.js, blank/README.md, blank/babel.config.js, blank/package.json, contributing.md
- Can be used for making new examples
- [README](https://github.com/expo/examples/blob/@evanbacon/blank/init/blank/README.md)
=> Created blank example

with-react-three-fiber/App.js, with-react-three-fiber/README.md, with-react-three-fiber/babel.config.js, with-react-three-fiber/package.json
=> Created react-three-fiber example

with-nextjs/.gitignore
`.next` should be in the gitignore.
=> Add .next to .gitignore

with-custom-font/App.js
We don't have to do this anymore 😄
=> Use built-in useFonts hook for custom fonts

with-electron/README.md
Fixes #218 
Would y'all mind adding the `hacktoberfest-accepted` label to this PR?
=> Update latest doc link in with Electron README

with-storybook/.gitignore
Otherwise all node_module will be added to git when init the project
=> Add node_modules to gitignore

with-development-client/ios/HelloWorld.xcodeproj/project.pbxproj, with-development-client/ios/HelloWorld/AppDelegate.m, with-development-client/ios/Podfile.lock
Updates installation steps - connected with https://github.com/expo/expo/pull/11681.
Also, I've removed the `start packager` scripts.
=> [with-development-client] Update package detection & remove 'start packager' script

with-development-client/README.md, with-development-client/app.json, with-development-client/eas.json, with-development-client/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/with-development-client.xcscheme
Adds EAS support to the example.
=> [with-development-client] Add EAS support

with-camera/App.js, with-camera/CameraPermissionsWrapper.js, with-camera/README.md, with-camera/babel.config.js, with-camera/package.json
Hey, here's a small PR for to add a template with a Camera. 
Let me know if my example should be lighter than this.
Relates to #168
=> with-camera

with-development-client/android/gradle.properties
=> [with-development-client] Remove heap limit on Android

with-dev-client/ios/Podfile.lock, with-dev-client/package.json
Bump to the latest version and recreate `Podfile.lock`
=> [with-dev-client] Bump to `0.1.3`

with-google-vision/package.json
=> [google-vision] Upgrade to Expo SDK 43

with-icons/package.json
=> [icons] Upgrade to Expo SDK 43

with-preact/package.json
=> [preact] Upgrade to Expo SDK 43

with-reanimated2/package.json
=> [reanimated2] Upgrade to Expo SDK 43

with-sqlite/package.json
I prefer double mountain dew light
=> [sqlite] Upgrade to Expo SDK 43

with-victory-native/package.json
Ok, so who of you thought it was funny to put a random lodash in the package list without actually using it?
=> [victory-native] Upgrade to Expo SDK 43 and Victory Native to 35

with-tfjs-camera/App.js, with-tfjs-camera/package.json, with-tfjs-camera/src/LoadingView.js, with-tfjs-camera/src/ModelView.js
Also added some tweaks to use the new Camera permission hook (avoiding the message about deprecated permissions).
=> [tfjs-camera] Upgrade to Expo SDK 43 and latest TFJS RN

with-styled-components/package.json
=> [styled-components] Upgrade to Expo SDK 43

with-workbox/package.json
=> [workbox] Upgrade to Expo SDK 43

with-apollo/package.json
New SDK new "hey, upgrade the examples please"
=> [apollo] Upgrade to Expo SDK 43

with-aws-storage-upload/App.js, with-aws-storage-upload/package.json
Works nicely had to go through the setup step of amplify and took a while. Hope my credit card isn't raided in a month.
=> [aws-storage-upload] Upgrade to Expo SDK 43 and Amplify 4

with-firebase-storage-upload/App.js, with-firebase-storage-upload/package.json
To whoever pays for the storage, I'm sorry, I had to test.
=> [firebase-storage-upload] Upgrade to Expo SDK 43 and Firebase 9

with-custom-font/package.json
=> [custom-font] Upgrade to Expo SDK 43

with-postpublish-hooks/package.json
=> [postpublish-hooks] Upgrade to Expo SDK 43

with-socket-io/App.js, with-socket-io/README.md, with-socket-io/backend/index.js, with-socket-io/backend/package.json, with-socket-io/package.json
@brentvatne is the https requirement still a thing? I managed to get it working with just my local IP, using http
=> [socket-io] Upgrade to Expo SDK 43

with-storybook/README.md, with-storybook/package.json
Maybe we should update storybook to v6?
=> [storybook] Upgrade to Expo SDK 43

with-magic/App.js, with-magic/package.json
Also updated some code things to make it slightly more readable.
=> [magic] Upgrade to Expo SDK 43 and Magic RN 6

with-google-vision/App.js
- Fix permission error
- Add info about the API Key
- Add extra permissions info
=> [with-google-vision] Improve approachability

with-postpublish-hooks/app.config.js, with-splash-screen/app.config.js, with-victory-native/app.config.js, with-webbrowser-redirect/app.config.js
This fixes an issue when publishing within the workflow, where the app.json isnt used
=> Add config inheritence to projects with app.config.js

with-react-native-elements/App.js, with-react-native-elements/README.md, with-react-native-elements/babel.config.js, with-react-native-elements/package.json
resolve https://github.com/expo/examples/issues/71
=> Created example for react-native-elements

with-pdf/App.js, with-pdf/README.md, with-pdf/app.json, with-pdf/babel.config.js, with-pdf/eas.json, with-pdf/index.js, with-pdf/metro.config.js, with-pdf/package.json
Created example of using react-native-pdf with out-of-tree config plugin in a custom Expo dev client.
=> Create react-native-pdf Example

.all-contributorsrc
I don't know why the bot didn't pick this up...
=> [docs] add kbrandwijk to contributors

.all-contributorsrc
=> Revert "[docs] add kbrandwijk to contributors"

with-splash-screen/App.js, with-splash-screen/package.json
1) Updated references to Constants.manifest to Constants.expoConfig.
2) Added scripts such that the instructions in the README.md work.
=> Minor fixes to get this to work

with-pdf/package.json
Updated with-pdf to use the latest version of react-native-pdf 6.6.2
=> Updated react-native-pdf to latest version 6.6.2

with-router/babel.config.js, with-router/index.js, with-router/package.json
drop resolutions that keep tripping users up
=> update router template

with-router-tailwind/README.md, with-router-tailwind/app.json, with-router-tailwind/babel.config.js, with-router-tailwind/global.d.ts, with-router-tailwind/metro.config.js, with-router-tailwind/package.json, with-router-tailwind/src/app/_layout.tsx, with-router-tailwind/src/app/index.tsx, with-router-tailwind/src/global.css, with-router-tailwind/tailwind.config.js, with-router-tailwind/tsconfig.json
Make it easy to bootstrap a project with router and nativewind v4
=> feat: router with tailwind demo

with-descope/App.js, with-descope/README.md, with-descope/babel.config.js, with-descope/package.json
This is an example of how you would use Descope as an OAuth provider with Expo and AuthSession.
=> Added Descope + Expo Sample App

with-tv/app.json, with-tv/package.json
- Move to SDK 50.0.6
- Move TV config plugin to dev dependencies, move to version 0.0.5
- Update react-native-tvos to 0.73.4-0
=> [with-tv] Update dependencies

with-react-compiler/.eslintrc.js, with-react-compiler/App.tsx, with-react-compiler/README.md, with-react-compiler/app.json, with-react-compiler/package.json, with-react-compiler/tsconfig.json
Depends on this landing and getting published https://github.com/expo/expo/pull/29168
=> feat: add react compiler example

with-sqlite/App.js
The SQLite example didn't work at all, due to the fact it used the old API.
I'm not sure I've used the best idioms for the new API (these are all the *Sync methods, for example), but at least it's up and running again.
I couldn't get the `useEffect` hook to create the `items` table in time, so that is pushed up into the connection creation function.
cc @brentvatne @alanjhughes
=> fix: Update with-sqlite example

with-tinybase/App.js, with-tinybase/package.json
As @brentvatne suggested! No change, cosmetically, but also uses SafeAreaView to be clean.
=> fix(with-tinybase) Introduce FlatList

with-libsql/App.tsx
updates example code to support offline-writes
=> [with-libsql] update for offline-writes

stickersmash/app/(tabs)/about.tsx, stickersmash/app/(tabs)/index.tsx, stickersmash/app/+not-found.tsx, stickersmash/app/_layout.tsx, stickersmash/components/Button.tsx, stickersmash/components/CircleButton.tsx, stickersmash/components/EmojiList.tsx, stickersmash/components/EmojiPicker.tsx, stickersmash/components/EmojiSticker.tsx, stickersmash/components/IconButton.tsx, stickersmash/components/ImageViewer.tsx
Fix ENG-15754
Fix TypeScript error for image source prop and default file formatting from Expo ESLint and Prettier rules. Follow-up improvements from docs: https://github.com/expo/expo/pull/36818
=> [stickersmash] Fix TypeScript error for image source prop and default file formatting
