expo/examples

- with-webbrowser-redirect/app/App.js
- with-webbrowser-redirect/app/app.json
- with-webbrowser-redirect/app/package.json
- with-webbrowser-redirect/app/yarn.lock
Fixes https://github.com/expo/expo/issues/2396.
In standalone apps `Linking.makeUrl` was failing silently due to non-existent `manifest.scheme`.
> Fix with-webbrowser-redirect example

- with-detox-tests/README.md
- with-facebook-auth/README.md
- with-formdata-image-upload/README.md
- with-postpublish-hooks/README.md
- with-react-native-calendars/README.md
- with-redux/README.md
- with-socket-io/README.md
- with-victory-native/README.md
- with-webbrowser-redirect/README.md
This "purges" the old references to Exp and XDE, replacing them with the latest Expo CLI. I also added a link to the docs, mostly for new developers not knowing about this tool yet.
Also, I fixed some references in readme's about a sub-`app`-folder. Those folders aren't using the app folders and might confuse some people, although it should be quite obvious 😄
These aren't using `app` folders: 
- with-facebook-auth
- with-postpublish-hooks
- with-react-native-calendars
- with-redux
> Replace exp and xde references with expo cli

- with-storybook/.storybook/config.native.js
- with-storybook/App.tsx
- with-storybook/package.json
- with-storybook/stories/0-Welcome.stories.js
- with-storybook/stories/1-Button.stories.js
- with-storybook/stories/2-Constants.stories.js
- with-storybook/stories/3-LinearGradient.stories.js
- with-storybook/stories/4-Font.stories.js
- with-storybook/stories/index.native.js
Updated the with-storybook example to show how you run @storybook/react-native on device.
It will just show when you kick off expo in a native simulator. 
Having a seperate `.native.js` config is pretty annoying but you can see there are lots of differences in how you get onDevice storybook running. Also no `require.context` on metro is less than great. I've tried [storybook-loader](https://github.com/elderfo/react-native-storybook-loader) before but it always flakes out on me.
Hope this helps
> [storybook][native] update storybook example to run on native device

- with-webbrowser-redirect/app/App.js
See https://github.com/expo/examples/issues/30 and https://github.com/expo/expo/issues/5555.
> For Android devices, call `_removeLinkingListener()` once the redirect back to the app has been handled

- with-animated-splash-screen/App.js
- with-animated-splash-screen/README.md
- with-animated-splash-screen/app.json
- with-animated-splash-screen/babel.config.js
- with-animated-splash-screen/package.json
Fixes #87
I wasn't sure if we should add [a link the snack](https://snack.expo.io/@bacon/animated-splash-screen). It might be better if we add [a link like the Facebook Auth](https://github.com/expo/examples/tree/master/with-facebook-auth#facebook-auth-example)?
> feat: add animated splash screen example

- with-twitter-auth/README.md
- with-twitter-auth/app/App.js
- with-twitter-auth/app/app.json
- with-twitter-auth/app/babel.config.js
- with-twitter-auth/app/package.json
- with-twitter-auth/backend/index.js
- with-twitter-auth/backend/package.json
Fixes #82 
Stuff I did after moving the Twitter auth example:
- **Added step-references to the [Login with Twitter guide](https://developer.twitter.com/en/docs/basics/authentication/guides/log-in-with-twitter)**
That guide is useful. It contains a lot of flow visualizations and info a developer needs to know. By adding references to these steps, they can follow the code with the guide.
- **Rewrite the `WebBrowser` flow with `AuthSession`**
Mostly because I think this is the preferred way, right? It avoids some heavier topics like deep linking. Or should I rewrite it to use [`AppAuth`](https://docs.expo.io/versions/latest/sdk/app-auth/)? Not sure what benefits you gain, I don't think Twitter allows you to authenticate without client secret?
- **Simplify the backend with [Twitter …
> feat: add login with twitter example

- with-sqlite/App.js
- with-sqlite/README.md
- with-sqlite/package.json
This also includes:
- A fix for using refs with functional components. Instead of this, it uses a `useForceUpdate` hook and the `key` property to force a rerender. Unfortuntately, refs doesn't work with functional components.
- Updated docs to reflect no support for web or snack. The docs states it has no web support, and the snack link failed. Also fixes #92
> refactor(with-sqlite): upgrade to sdk 37

- with-custom-font/package.json
I also noticed `expo-font` was missing from the `package.json`, this adds that too. 😄
> refactor(with-custom-font): upgrade to expo sdk 37

- with-animated-splash-screen/package.json
- with-auth0/package.json
- with-custom-font/package.json
- with-electron/package.json
- with-facebook-auth/package.json
- with-firebase-storage-upload/package.json
- with-formdata-image-upload/app/package.json
- with-gatsby/package.json
- with-google-vision/package.json
- with-icons/package.json
- with-postpublish-hooks/package.json
- with-preact/package.json
- with-react-router/package.json
- with-socket-io/app/.babelrc
- with-socket-io/app/babel.config.js
- with-socket-io/app/package.json
- with-sqlite/package.json
- with-storybook/package.json
- with-twitter-auth/app/package.json
- with-typescript/package.json
- with-victory-native/package.json
- with-video-background/package.json
- with-webbrowser-redirect/app/package.json
expo installs babel-preset-expo so we don't need to depend on it in every project. We do need to install babel/core tho.
Also add react-native-web to all projects
> Use babel/core with babel-preset-expo in expo

- with-storybook/README.md
The @expo/webpack-config is needed by the webpack.config.js.
> Add @expo/webpack-config command to Readme

- with-video-background/App.js
Fixes a TypeScript error when using this example with TypeScript, since it expects `useNativeDriver` to be defined. Also follows the example of [with-animated-splashscreen](https://github.com/expo/examples/blob/6bfc52cc335203e70d8d3fb8aa116992db4af6c8/with-animated-splash-screen/App.js#L55).
>  Add `useNativeDriver` to with-video-background example

- with-magic/App.js
- with-magic/README.md
- with-magic/package.json
This adds a basic example on how to perform Magic.link authentication 😄  (shout out to @Ethella for making it work smoothly in Expo)
> feat: add magic link authentication example

- with-facebook-auth/App.js
This will close #194. This bug is easily reproducible by pulling down a fresh copy of the repo, running the with-facebook app in expo, following the setup steps, and then attempting a login. It will error with `No redirect URI in the params: No redirect present in the URI` because it's attempting to use `exp://...` url to redirect.
Correct redirectUri is already created above and includes the useProxy. https://github.com/hostr/examples/blob/481380b024cacaa770ff860c87d70fdb342f424b/with-facebook-auth/App.js#L18
> Fix issue with incorrect Facebook redirectUri

- with-reanimated2/App.js
- with-reanimated2/README.md
- with-reanimated2/app.json
- with-reanimated2/babel.config.js
- with-reanimated2/package.json
Won't work until we release SDK 39 (although on iOS we already released the SDK 39 client in the simulator, so people can use it now if they want). This did not run on web for me, not sure if it's meant to.
> Add with-reanimated2

- with-nextjs/README.md
Update the link in the nextjs example `README.md` which points to the freshest expo next.js docs. The link currently specified,
`https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/using-nextjs.md`
Leads to '404 Page not Found'.
@EvanBacon - I noticed the link on [this blog post of yours](https://dev.to/evanbacon/next-js-expo-and-react-native-for-web-3kd9) has the same issue (`ctrl+f` "Here are the latest docs on master.") -- i.e. it points to `*/versions/unversioned*`.
> docs: update latest docs link to expo repo

- with-storybook/README.md
- The `webpack-config` instruction was duplicated
- Storybook is started with `yarn storybook`, not `yarn web`
- Added link to Storybook React docs
> Fix command & remove duplicate

- with-development-client/ios/Podfile.lock
- with-development-client/package.json
expo-dev-launcher: `0.1.2` -> `0.2.0`
expo-dev-menu: `0.1.2` -> `0.3.0`
expo-dev-menu-interface: `0.1.1` -> `0.1.2`
> [with-development-client] Bump versions

- with-moti/package.json
- with-moti/webpack.config.js
Add support for Expo Web in the Moti template.
Moti uses Reanimated v2 under the hood. Without transpiling it, the Reanimated Babel plugin is not applied on Web, causing Moti to break. This solves that.
> [with-moti] web support

- with-tfjs-camera/App.js
- with-tfjs-camera/README.md
- with-tfjs-camera/babel.config.js
- with-tfjs-camera/package.json
- with-tfjs-camera/src/LoadingView.js
- with-tfjs-camera/src/ModelView.js
- with-tfjs-camera/src/PredictionList.js
- with-tfjs-camera/src/useTensorFlow.js
- The official native TensorFlow package uses Expo Camera and Expo GL https://js.tensorflow.org/api_react_native/latest/#Media-Camera. 
- CV is kewl.
> Created tfjs camera example

- with-dev-client/android/app/src/main/java/com/helloworld/MainActivity.java
- with-dev-client/android/app/src/main/java/com/helloworld/MainApplication.java
- with-dev-client/index.js
- with-dev-client/ios/HelloWorld/AppDelegate.m
- with-dev-client/ios/Podfile.lock
- with-dev-client/package.json
Bump versions to use the newest dev client and SDK.
- Android  - ok
- iOS - ok       
> [with-dev-client] Bump to `0.4.3`

- with-gatsby/package.json
I did not look into upgrading Gatsby here but seems like we should.
> [gatsby] Upgrade to Expo SDK 43

- with-react-three-fiber/package.json
[Can't upgrade react three fiber because of this issue](https://github.com/pmndrs/react-three-fiber/issues/1506). TL;DR; they shipped a version with a `react-native` target/entry file without that file actually existing.
> [react-three-fiber] Upgrade to Expo SDK 43

- with-tab-navigation/App.js
- with-tab-navigation/package.json
Also added some default tab icons, it looked a bit sad without them.
> [tab-navigation] Upgrade to Expo SDK 43 and React Navigation 6

- with-react-router/README.md
- with-react-router/package.json
Also added Android and iOS support, since we actually do in this example.
> [react-router] Upgrade to Expo SDK 43 and bump React Router

- with-formik/package.json
Seems pretty stable, still on the same formik + yup minor/major versions
> [formik] Upgrade to Expo SDK 43

- with-splash-screen/package.json
Luckily this one is with a screen, without it the splash would look more like:
> [splash-screen] Upgrade to Expo SDK 43

- with-auth0/package.json
Works well, it only has a warning about the missing scheme. But in this case that makes sense since we want people to use their own instead of copying blindly.
> [auth0] Upgrade to Expo SDK 43

- with-formdata-image-upload/App.js
- with-formdata-image-upload/package.json
Had to change the API endpoint, since that was no longer found. And sharing/copying huge base64 doesn't work that well, so the share and copy to clipboard are also gone.
> [formdata-image-upload] Upgrade to Expo SDK 43

- with-electron/package.json
I chickened out on upgrading electron as well. We might need to do that eventually.
> [electron] Upgrade to Expo SDK 43

- with-facebook-auth/package.json
I wonder when we have to rename this to `with-metaverse-auth`
> [facebook-auth] Upgrade to Expo SDK 43

- with-drawer-navigation/package.json
“Be the git diff that you wish to see in the world.”
― Mahatma Gandhi
> [drawer-navigation] Upgrade to Expo SDK 43 and React Navigation 6

- with-svg/package.json
SVGs are used as [inline images for 97.05% of all usage](https://css-tricks.com/random-interesting-facts-htmlsvg-usage/#svg)
> [svg] Upgrade to Expo SDK 43

- with-three/package.json
With a warning though: 
```
EXGL: gl.pixelStorei() doesn't support this parameter yet!
```
If we don't support three anymore, maybe its better to remove this one.
> [three] Upgrade to Expo SDK 43

- .github/workflows/preview.yml
This is a basic version of the one I created at [bycedric/eas-monorepo-example](https://github.com/byCedric/eas-monorepo-example/pull/25). It has a couple of advantages over hardcoding paths:
- Check whatever example was changed
- Create parallel actions to publish
It's a start, I'll comment on some things we might want to consider
> Add basic preview workflow

- with-typescript/package.json
In the wake of this PR https://github.com/expo/examples/pull/339
I just want to update the react-native version to the current version (0.64.3) according to https://github.com/expo/expo/pull/15108
> [with-typescript] Update react-native to 0.64.3 to match the updated Expo SDK@43

- with-processing/App.js
- with-processing/README.md
- with-processing/babel.config.js
- with-processing/package.json
Probably not the best idea since processing-js is archived in favor of p5, but resolves https://github.com/expo/examples/issues/61
> Created processing example

- with-realm/App.tsx
- with-realm/README.md
- with-realm/app/components/AddTaskForm.tsx
- with-realm/app/components/IntroText.tsx
- with-realm/app/components/TaskItem.tsx
- with-realm/app/components/TaskList.tsx
- with-realm/app/models/Task.ts
- with-realm/app/styles/colors.ts
- with-realm/babel.config.js
- with-realm/eas.json
- with-realm/index.js
- with-realm/metro.config.js
- with-realm/package.json
With the release of SDK 44 and the `expo-dev-client`, `realm` can
finally work with Expo!  
This example is based off of the templates
already existing in [RealmJS](https://github.com/realm/realm-js) and the `with-dev-client` Expo example
> Add with-realm example

- with-realm/README.md
The command in the README.md was using `npx expo-cli` instead of `npx create-react-native-app`.
This has been updated avoid confusion.
> Fix up project init command

- with-firebase-saml-login/metro.config.js
- with-firebase-storage-upload/metro.config.js
- with-firebase-storage-upload/package.json
**Why?**
https://github.com/expo/expo/issues/17469
**How?**
Added `cjs` to the source extensions.
> fix: firebase examples upstream breaking change

- with-splash-screen/README.md
This PR removes Expo AppLoading reference from the `with-splash-screen` Readme file.
> [docs][with-splash-screen]: Update README.md

- with-sqlite/package.json
The README tells you to run the project via `yarn start` but there is no script specified to do so in `package.json`.
> [with-sqlite] add scripts to run example

- with-router/package.json
See: https://github.com/expo/router/issues/13
> fix(with-router): bump Metro to include windows posix fix

- with-twitter-auth/README.md
Not sure if this is a new thing, but adding `exp://` as a callback URL was necessary for me to get the Twitter Auth Example working. Adding this PR to help alleviate stress to anyone new trying to get it working after me.
> Add exp:// as AuthSession callback URL for Twitter-Auth Example

- with-twitter-auth/backend/index.js
In regards to completing step #3 in the 3-legged OAuth flow, the options need to be renamed. This was a costly bug I came across.
> Fixing backend issue

- with-nativewind/App.js
- with-nativewind/README.md
- with-nativewind/app.json
- with-nativewind/babel.config.js
- with-nativewind/package.json
- with-nativewind/tailwind.config.js
I have added [NativeWind](https://www.nativewind.dev/) example in this pull request. NativeWind allows us to use Tailwind CSS in react-native. I know that there is already one example with tailwind-rn but I felt that NativeWind feels more similar to using Tailwind CSS on the web, and provides better intellisense.
> add with-nativewind example

- with-facebook-auth/README.md
Currently, the instructions to set up Facebook app are outdated
This PR:
- Updates the outdated instructions and updates Facebook app dashboard screenshots
- Fixes links to Expo docs
- Removes the outdated Expo Go example link since that example doesn't work anymore and is not supported with the latest app version
Will be updating the instructions in a future PR and adding a link to the guide from the docs.
> [docs][with-facebook] Update outdated instructions for Facebook example

- with-router/package.json
See: https://expo.github.io/router/docs/#getting-started
> fix(router): define `main` entrypoint in `package.json`

- with-custom-font/App.js
There are 3 things that I want to improve.
Prettier was not applied to all lines of this example.
According to the [SplashScreen Method](https://docs.expo.dev/versions/latest/sdk/splash-screen/#methods) section, `preventAutoHideAsync` method is recommended to be called in global scope without awaiting because otherwise this might be called too late.
However, in this example, `preventAutoHideAsync` is called inside of `useEffect` hook. So I updated this.
If an error occurs while fetching remote fonts, the splash screen should be hidden and the platform default font can be used rather than keep showing splash screen.
https://docs.expo.dev/develop/user-interface/fonts/#minimal-example
> Update with-custom-font example

- with-facebook-auth/package.json
This commit adds the missing **'start script'** to the `package.json`  file of the **'with-facebook-auth'** example. This script is necessary for running the example correctly.
**Note:** The documentation currently states to run the program using 'yarn' and 'yarn start'. However, running these commands alone results in the error 'Command "start" not found'.
To address this issue, I added the missing startup script to the package.json file. After adding the following script:
```
"scripts": {
"start": "expo start"
}
```
The program can now be executed successfully using: **`'yarn start'`** or **`'expo start'`** or **`'npm run start'`**. This ensures the proper startup of the application.
> Add start script to package.json

- .github/workflows/preview.yml
The GitHub "preview" workflow relies on the outdated global Expo CLI, specifically `expo publish`, which no longer works in SDK 49 and later (it is part of classic updates). Disabling the workflow until a decision is made to fix or remove it.
> Disable outdated preview workflow

- with-gatsby/README.md
We do not have Using Gatsby guide anymore. This PR removes the removed link from the `with-gatsby/README.md` example.
> [with-gatsby] Remove docs link

- with-nextjs/package.json
This bumps the `with-nextjs` example to Next 14 and the adapter v6 (which contains peer dependency version loosening)
See: https://github.com/expo/expo-webpack-integrations/pull/25
> chore(with-nextjs): update to `next@14` with `@expo/next-adapter@6`

- .github/workflows/upgrade.yml
- .gitignore
- upgrade-dependencies.sh
If this works well, we can also schedule the `--fix-dependencies` through a corn job.
> chore: add workflow to keep dependencies up-to-date

- with-storybook/.storybook/main.js
This PR fixes the following error:
```
Error: Cannot find package '@babel/plugin-proposal-export-namespace-from' imported from ~/expo/examples/with-storybook/babel-virtual-resolve-base.js
```
It is safe to remove this babelPlugin, as it is not used by any of the packages in the example, see also: [docs](https://github.com/storybookjs/addon-react-native-web/?tab=readme-ov-file#adding-babel-plugins).
- clone the Expo Examples repository: `git clone git@github.com:expo/examples.git`
- `cd with-storybook`
- `npm install`
- `npm run storybook`
- You will see the error
Similarly the fix can be reproduced by navigating to the fix branch.
> [with-storybook] Fix error after upgrading to Expo SDK 50

- README.md
- contributing.md
- with-dev-client/README.md
- with-moti/README.md
- with-native-base/README.md
- with-pdf/README.md
- with-react-three-fiber/README.md
- with-realm/README.md
- with-reanimated/README.md
- with-tfjs-camera/README.md
- with-typescript/README.md
- with-webrtc/README.md
- with-workbox/README.md
- with-yarn-workspaces/README.md
This moves all `create-react-native-app` references to `create-expo`.
> docs: switch to `create-expo` to unify example creation

- with-tinybase/App.js
- with-tinybase/README.md
- with-tinybase/babel.config.js
- with-tinybase/package.json
Here's a new template that uses TinyBase (and Expo SQLite) to implement a simple todo app.
WYSIWYG!
> Add TinyBase example

- with-router-tv/README.md
- with-tv/README.md
- with-tv/package.json
Added the scripts for with-tv and modified the README to include a description of why the EXPO_TV=1 is needed.
> Fix: Add scripts and modify README for tv examples

- with-nextjs/next.config.js
Fixes an issue reported on the main expo's repo: https://github.com/expo/expo/issues/31272 
Checkout the `ssr-issue-fix` which contains both the fix and a background color on the page (which isn't added to the example in the PR), used to verify the fix.
```bash
git clone git@github.com:illbexyz/examples.git \
&& cd examples \
&& git checkout ssr-issue-fix \
&& cd with-nextjs \
&& npm install
```
Start the example and verify that the styles are now being correctly added to the html document.
> fix(with-nextjs): transpile react-native-web to fix ssr styles

- with-router-tailwind/src/app/index.tsx
> fix: typo on with-router-tailwind

- with-shadcn/README.md
- with-shadcn/app.json
- with-shadcn/components.json
- with-shadcn/package.json
- with-shadcn/postcss.config.js
- with-shadcn/src/app/+html.tsx
- with-shadcn/src/app/_layout.tsx
- with-shadcn/src/app/index.tsx
- with-shadcn/src/components/ui/badge.tsx
- with-shadcn/src/components/ui/button.tsx
- with-shadcn/src/components/ui/drawer.tsx
- with-shadcn/src/components/ui/input.tsx
- with-shadcn/src/components/ui/label.tsx
- with-shadcn/src/components/ui/select.tsx
- with-shadcn/src/components/ui/textarea.tsx
- with-shadcn/src/components/ui/tooltip.tsx
- with-shadcn/src/global.css
- with-shadcn/src/lib/utils.ts
- with-shadcn/tailwind.config.js
- with-shadcn/tsconfig.json
Shadcn CLI no longer aids in the setup of Expo Router projects since it isn't one of the recognized frameworks. So I'm adding a slightly opinionated example to make all the requirements (things like postcss, tailwind, autoprefixer, etc) easy to setup.
This demo is web-only and won't run on native. We can add native shims in SDK 52 with DOM components.
> add shadcn demo

- stickersmash/app/(tabs)/index.tsx
- stickersmash/app/_layout.tsx
Using the `StatusBar` component in the child component or root layout of Expo Router does not affect the status bar style changes (applied through code) every time the app is re-rendered in the dev mode.
Using `setStatusBar` with a `useEffect` ensures that any time the app loads, the status bar style is applied before app loads.
> Render StatusBar before app loads in StickerSmash app

- stickersmash/app/(tabs)/index.tsx
- stickersmash/components/EmojiList.tsx
- stickersmash/components/EmojiSticker.tsx
- stickersmash/components/ImageViewer.tsx
Follow-up [#32115](https://github.com/expo/expo/pull/32115)
Fix type missing issue when an image is used inside any custom component.
> Add ImageSource type to fix TypeScript issues where Expo Image is used

- stickersmash/components/EmojiPicker.tsx
Fix emoji picker modal not displayed on re-open on Android.
> [stickersmash] Fix Modal not opening on re-adding sticker for Android

- with-router-tv/README.md
- with-router-tv/app.json
- with-router-tv/app/(tabs)/_layout.tsx
- with-router-tv/app/(tabs)/tv_focus.tsx
- with-router-tv/components/EventHandlingDemo.tsx
- with-router-tv/package.json
Improve `with-router-tv` to support web, as well as TV and mobile targets.
> TV router example to Expo 52.0.46, add web support

- stickersmash/README.md
- stickersmash/package.json
- with-maestro/README.md
- with-maestro/package.json
- with-openai/README.md
- with-openai/package.json
- with-react-flow/README.md
- with-react-flow/package.json
- with-router-menus/README.md
- with-router-menus/package.json
- with-router-tailwind/README.md
- with-router-tailwind/package.json
- with-router-tv/README.md
- with-router-tv/package.json
- with-router/README.md
- with-router/package.json
- with-rsc/README.md
- with-rsc/package.json
- with-satori/README.md
- with-satori/package.json
- with-stripe/README.md
- with-stripe/package.json
- with-tailwindcss/README.md
- with-tailwindcss/package.json
- Add deploy script to all router projects for web deployment.
- Add deployment section to readme of all router projects to add info about deploying the app/website.
> add deploy command to all router projects and add deployment info

- with-github-remote-build-cache-provider/build-cache-provider/src/index.ts
- with-github-remote-build-cache-provider/package.json
Update GitHub build provider example to reflect https://github.com/expo/expo/pull/36643 changes
> Update github cache provider to use buildCacheProvider

- with-webrtc/package.json
This PR upgrades the version of react-native-webrtc to a more recent version of v124, along with the version bump of the respective config-plugin to 12.0.0 (since version 11.0.0 doesn't exist as per the config plugin [table here](https://github.com/expo/config-plugins/tree/main/packages/react-native-webrtc#versioning))
This version bump is needed to solve the desugaring option deprecation issue on Android.
> Upgrade `with-webrtc` to use `react-native-webrtc` v124
